default_language_version:
  python: python3.10 # NOTE: this should align with the version in the various pyproject.toml files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-toml

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-crlf

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.6.0
    hooks:
      - id: pretty-format-ini
        args: [--autofix]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        # Why '--strict'? To return a non-zero exit code on warnings
        # so pre-commit captures it as a failure.
        args: [--strict, --config-file, .yamllint.yaml]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: typedstream

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: typedstream

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.276
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: easyocr

  - repo: local
    hooks:
      # https://github.com/hadolint/hadolint
      - id: dockerfile-lint
        name: Dockerfile Lint
        language: docker_image
        entry: hadolint/hadolint:v2.12.0 hadolint
        files: ^.*Dockerfile.*$

        # https://github.com/koalaman/shellcheck
      - id: shellcheck-lint
        name: Shellcheck
        language: docker_image
        entry: koalaman/shellcheck:v0.9.0
        types: [shell]
        exclude: ^(archiver/coordinator/src/coordinator/scripts/wallpaper/)

        # https://github.com/igorshubovych/markdownlint-cli
      - id: markdown-lint
        name: Markdown Lint
        language: docker_image
        entry: ghcr.io/igorshubovych/markdownlint-cli:v0.32.2
        args: [--config, .markdownlintrc, --fix]
        types: [markdown]

      # Some tools require local installation
      - id: lint
        name: lint
        entry: just lint-python
        language: system
        pass_filenames: false
        types: [python]
